### PR TITLE
v2.3.0

### PR DESCRIPTION
**Pull request by martiliones**
## Added

- `adm init [path]` command that allows to copy default config to `~/.adm/` or the given path:

  ```bash
  # to copy to ~/.adm/$ADM_CONFIG_FILENAME
  $ adm init
  # to copy to the specific directory
  $ adm init ./my-dir
  ```

### CODE REVIEW

**Review by adamant-al — APPROVED** [review]

**Comment by bludnic** [comment]
It may be not related to the current PR. The package.json uses `>=14` as a node engine but the docs requires `>=v18`
https://github.com/Adamant-im/adamant-console/wiki/Installation-and-configuration

**Comment by bludnic** [comment]
Do I run it correctly? @martiliones 

1. Cloned the branch
2. Run `npm install`
3. Executed `./bin/adamant.js init`. Updated "passphrase" and changed "network" to "mainnet".
4. Sending a message: `./bin/adamant.js send message U9203183357885757380 "hi"`

Expected: Message sent

Actual:
```
Exception in PromiseRejectCallback:
file:///Users/bludnic/Adamant/adamant-console/lib/api/send.js:47
  return res.data || res;

RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:
file:///Users/bludnic/Adamant/adamant-console/lib/api/send.js:38
  const res = await sendMessage(
                    ^

RangeError: Maximum call stack size exceeded

{
  "success": false,
  "error": "RangeError: Maximum call stack size exceeded"
}
```

**Comment by adamant-al** [comment]
@bludnic Please check it once again with the fix applied.

**Comment by bludnic** [comment]
Got and error when using `adm send signal` command:

```
{
  "success": false,
  "error": "Wrong 'type' parameter: signal"
}
```

This must fix: `const messageType = 'signal';` -> `MessageType.Signal`
https://github.com/Adamant-im/adamant-console/pull/31/files#diff-43489343641ef5ff20e9a236c2ab00a4bddce6d7fd217ee06ec75c8e5d1fc420R76

**Review by bludnic — APPROVED** [review]

**Pull request merged**
