### PR TITLE
V2.4.0

### PR DESCRIPTION
**Pull request by martiliones**

### CODE REVIEW

**Comment by martiliones** [comment]
waiting for https://github.com/Adamant-im/adamant-api-jsclient/pull/57

**Comment by adamant-al** [comment]
```
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: adamant-console@2.4.0
npm ERR! Found: eslint@9.1.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.32.0 || ^8.2.0" from eslint-config-airbnb-base@15.0.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^15.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

Will we do something with it?
Will it influence on `npm install -g adamant-console`?

`pnpm install` works well.

**Comment by adamant-al** [comment]
```
> send message U15531909278942872097 "Hello"
{
  "success": true,
  "nodeTimestamp": 209573947,
  "transactionId": "9329817377467460348"
}
```

⟶

```
> get message 9329817377467460348
{
  "success": true,
  "nodeTimestamp": 209573956,
  "transaction": {
    "id": "9329817377467460348",
    "height": 40033196,
    "blockId": "9784287158004791648",
    "type": 8,
    "block_timestamp": 209573955,
    "timestamp": 209573947,
    "senderPublicKey": "bc3a58739dd875869e6fbda17776b90d30c1ccf59c317c45f0dbbbbfa67464af",
    "senderId": "U11682340443943600267",
    "recipientId": "U15531909278942872097",
    "recipientPublicKey": "fb736e72b4df38d973f0f8dfccbece763ab0d9603897dfa8f1167fa50018a8e0",
    "amount": 0,
    "fee": 100000,
    "signature": "4309ed9fa1fdf905fb8edc6dc353321f4fbfbb55ba716b7de009b0035692b1e0c71e6e78dd76818f422611fe776706a7a265b9b85e9fdbbb6c7ef14306e27601",
    "signatures": [],
    "confirmations": 1,
    "asset": {
      "chat": {
        "message": "Hello",
        "type": 1
      }
    }
  }
}
```

How do we know if `transaction.asset.chat.message` contains encrypted message or already decrypted?

**Comment by adamant-al** [comment]
```
> send message U15531909278942872097 "Hello-ADM" 0.11ADM
{
  "success": true,
  "nodeTimestamp": 209574507,
  "transactionId": "5088544052328804510"
}
```

*0 sec await* ⟶ 

```
> get message 5088544052328804510
{
  "success": false,
  "error": "Not a message transaction"
}
```

Expected: Transaction not found.

**Comment by adamant-al** [comment]
@martiliones 
Is it possible not to downgrade eslint version?

**Comment by martiliones** [comment]
@adamant-al 
The `eslint-config-airbnb-base` plugin, which contains all the rules that the repository's style is based on, is not yet ready for `eslint` v9.

**Comment by martiliones** [comment]
- [x] update docs for `transaction.decoded` in `get message` response

**Review by adamant-al — APPROVED** [review]

**Comment by adamant-al** [comment]
@bludnic Check the PR.

**Review by bludnic — APPROVED** [review]

**Comment by adamant-al** [comment]
Release.

**Comment by adamant-al** [comment]
@martiliones 
Merge and release.

**Comment by martiliones** [comment]
> How do we know if `transaction.asset.chat.message` contains encrypted message or already decrypted?

In the previous version, if the message wasn't decrypted it included `chat.own_message`.

Was it the right call to introduce a breaking change then? 🤔

**Pull request merged**
